AdminPanel/Controllers/EpisodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPanel.Controllers
{
    public class EpisodeController : Controller
    {
        private AppDbContext _context { get; }
        public EpisodeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int id)
        {
            var movies = await _context.Episodes
            .Where(x => x.SeasonsId == id).ToListAsync();
            return View(movies);
            
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Episode episode)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Episode NewEpisode = new Episode
            {
                Name = episode.Name,
                LanguageId = 1

            };
            await _context.Episodes.AddAsync(NewEpisode);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AdminPanel/Controllers/SeasonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPanel.Controllers
{
    public class SeasonController : Controller
    {
        private AppDbContext _context { get; }
        public SeasonController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int id)
        {
             var movies = await _context.Seasons
                      .Where(x => x.TvSeriesId == id).ToListAsync();
               return View(movies);
            
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Season season)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Season NewSeason = new Season
            {

            };
            await _context.Seasons.AddAsync(NewSeason);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AdminPanel/Views/Season/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

AdminPanel/Views/Season/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Season> seasons = Model;
    int count = 1;
}

<div class="container">
    <div class="row">
        <h4 class="card-title"></h4>
        <a class="btn btn-success" asp-action="Create" style="width:150px; height:35px">Create Season</a>
        <div class="col-12">
            <table class="table table-image">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Imdb Id</th>
                        <th scope="col">Original Language</th>
                        <th scope="col">Title</th>
                        <th scope="col">ReleaseDate</th>
                        <th scope="col">Budget</th>
                        <th scope="col">SeasonNumber</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var series in seasons)
                    {
                        <tr>
                            <th scope="row">@count</th>
                            <td>@series.EpisodeCount</td>
                            <td>@series.SeasonNumber</td>
                            <td>
                                <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@series.Id"><i class="mdi mdi-delete-variant"></i></a>
                                <a class="btn btn-sm btn-danger" asp-action="Update" asp-route-id="@series.Id"><i class="mdi mdi-lead-pencil"></i></a>
                                <a class="btn btn-sm btn-danger" asp-controller="Episode" asp-action="Index" asp-route-id="@series.Id"><i class="mdi mdi-details"></i></a>
                            </td>
                        </tr>
                        count++;

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>